# Generated by Django 5.2.4 on 2025-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
