# Generated by Django 5.2.4 on 2025-08-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_at", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("returned_at", models.DateField(blank=True, null=True)),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_returned", models.BooleanField(default=False)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="books.book",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-borrowed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "profile", "returned_at"),
                        name="unique_active_loan_per_book",
                    )
                ],
            },
        ),
    ]
