# Generated by Django 5.2.4 on 2025-08-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
